### ISSUE TITLE
Suggestion: Spells as attributes

### ISSUE THREAD

**Issue by KiraKayn** [SiverDX/additional_attributes#3]
Not sure if this would be possible, but if you manage to do it I'd love that,  we could just give the attribute to a specific item using crafttweaker or smth, which would be hella useful

**Comment by Gabalus** [comment]
Man, just use /cast command

**Comment by meeprdib** [comment]
Having the spells be able to be enabled via attributes vs using /cast would allow for things like skill trees granting spells to a player or enabling Apotheosis gems/affixes to give spells. It's way more flexible than having to mess with commands imo. Might be worth checking this out if this feature will be considered [https://github.com/iron431/irons-spells-n-spellbooks/blob/1.19.2/src/main/java/io/redspace/ironsspellbooks/api/spells/ISpellContainer.java#L13](url)

**Comment by SiverDX** [comment]
Was initially hesitant on adding even more attributes related to spells since there are already quite a lot
But maybe it doesn't really matter, will look into this I suppose

**Comment by SiverDX** [comment]
Luckily the mod already supports this idea through the `SpellSelectionEvent`
**Testversion**: [additional_attributes-1.20.1-1.1.0-all.zip](https://github.com/user-attachments/files/16569632/additional_attributes-1.20.1-1.1.0-all.zip)

![image](https://github.com/user-attachments/assets/b1442ee2-4f1f-47a8-ad98-31e9411f431b)

**School**:
`additional_attributes:innate_school/<namespace>/<school>`
e.g. `additional_attributes:innate_school/irons_spellbooks/fire`

**Spell**:
`additional_attributes:innate_spell/<namespace>/<spell>`
e.g. `additional_attributes:innate_spell/irons_spellbooks/cloud_of_regeneration`

Base values get added together
Meaning if the school fire has a base of 3 and the firebolt spell has a base of -1 the resulting base will be 2 for that spell
(The modifiers like addition etc. will be calculated with that base)

**Comment by meeprdib** [comment]
I'll mess around with this later today, I'll report back if I come across any issues. Thank you for considering this idea!

**Comment by meeprdib** [comment]
Did some testing, and it seems to work flawlessly as far as I can tell. Both the innate school and innate spell attributes work as intended. There was a minor visual bug upon dying, where the spells still showed in the bottom left corner after the player has died and had their attributes reset, but this is fixed by pressing the spell cast key. I'm 95% sure this issue is caused by ISS itself though, as I recall someone having a similar issue earlier.

**Comment by SiverDX** [comment]
Released a version:
- https://www.curseforge.com/minecraft/mc-mods/additional-attributes/files/5634207
- https://modrinth.com/mod/additional-attributes/version/1.1.0

Future things to look at:
- update spell selection on death
- what to do with eldritch - unlock if present as attribute?
- selecting spells could break if some mod is spamming attribute updates for these attributes
  - don't know if any mod is doing sth. like that at the moment

**Comment by meeprdib** [comment]
As for the eldritch school, I think it could be locked even if the player has the attribute present, because people working with the mod can easily run the `/learnSpell` command in most contexts that they want the spells to be unlocked for the player, since it only needs to be ran once. Either that, or have a config for if the attribute should unlock the spell or not. I feel like the first one could get finnicky in implementation though, so I'm vouching for the config option or some sort of equivalent.

**Comment by SiverDX** [comment]
![image](https://github.com/user-attachments/assets/2d239284-6d41-4242-bff4-a349ed2bc56d)

![image](https://github.com/user-attachments/assets/0d28f2e7-e095-4ef1-bde5-250a0e6b6f7c)

Added support for all spells (by unfreezing & re-freezing the attribute registry)
Used this for testing: https://www.curseforge.com/minecraft/mc-mods/to-tweaks-irons-spells

Syntax for spell level attribute from third-party spells is:
- `additional_attributes:spell/<namespace>/<path>` (e.g. `additional_attributes:spell/traveloptics/orbital_void`)
  - instead of `spell_type_` (...)
- `additional_attributes:school/<namespace>/<path>`
  - instead of `spell_school_` (...)

There is no difference in syntax for innate spells

Keep in mind that there is no translation for these attributes by default
(Since I use [data generation](https://forge.gemwire.uk/wiki/Datageneration) which doesn't run when you actually play the game)

---

Also added two configs:
- Client config to not add an innate spell if an equally or more powerful version is already present in the selection
- Server config to unlock eldritch spells if the innate school or spell attribute is above 0

---

[additional_attributes-1.20.1-1.2.0-all.zip](https://github.com/user-attachments/files/16707234/additional_attributes-1.20.1-1.2.0-all.zip)

**Comment by efficient-efi** [comment]
> Luckily the mod already supports this idea through the `SpellSelectionEvent` **Testversion**: [additional_attributes-1.20.1-1.1.0-all.zip](https://github.com/user-attachments/files/16569632/additional_attributes-1.20.1-1.1.0-all.zip)
> 
> ![image](https://github.com/user-attachments/assets/b1442ee2-4f1f-47a8-ad98-31e9411f431b)
> 
> **School**: `additional_attributes:innate_school/<namespace>/<school>` e.g. `additional_attributes:innate_school/irons_spellbooks/fire`
> 
> **Spell**: `additional_attributes:innate_spell/<namespace>/<spell>` e.g. `additional_attributes:innate_spell/irons_spellbooks/cloud_of_regeneration`
> 
> Base values get added together Meaning if the school fire has a base of 3 and the firebolt spell has a base of -1 the resulting base will be 2 for that spell (The modifiers like addition etc. will be calculated with that base)

How did you add innate school attributes to an item?
I am currently using attributizer mod, but it doesn't recognize these as attributes, it's probably because it contains "/"?

**Comment by SiverDX** [comment]
`/` is part of a valid resource location so that will not cause issues
I added it through a (neo)forge event (in-code)

But the mentioned mod works for me

<img width="2199" height="1083" alt="Image" src="https://github.com/user-attachments/assets/9a5b11f9-b623-4c21-9f7f-e67a95ff67a3" />

``` json
{
  "minecraft:iron_chestplate":[
    {
      "attribute": "additional_attributes:innate_spell/irons_spellbooks/cloud_of_regeneration",
      "modify": 2,
      "uuid": "a516026a-bee2-4014-bcb6-b6a5775553de",
      "operation": "ADDITION"
    }
  ]
}
```

~~Though the `ADD_VALUE` seems to be broken / their github code does not match their released state~~
Actually might just have been added with 1.21
```
java.lang.IllegalArgumentException: No enum constant jackiecrazy.attributizer.ItemAttributeMod.Operation.ADD_VALUE
	at java.base/java.lang.Enum.valueOf(Enum.java:273)
	at TRANSFORMER/attributizer@3.1/jackiecrazy.attributizer.ItemAttributeMod$Operation.valueOf(ItemAttributeMod.java:53)
	at TRANSFORMER/attributizer@3.1/jackiecrazy.attributizer.ArmorAttributizer.lambda$apply$4(ArmorAttributizer.java:126)
```

**Comment by efficient-efi** [comment]
> `/` is part of a valid resource location so that will not cause issues I added it through a (neo)forge event (in-code)
> 
> But the mentioned mod works for me
> 
> <img alt="Image" width="2000" height="1083" src="https://private-user-images.githubusercontent.com/22003703/492009055-9a5b11f9-b623-4c21-9f7f-e67a95ff67a3.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTg0NTIwMzgsIm5iZiI6MTc1ODQ1MTczOCwicGF0aCI6Ii8yMjAwMzcwMy80OTIwMDkwNTUtOWE1YjExZjktYjYyMy00YzIxLTlmN2YtZTY3YTk1ZmY2N2EzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA5MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwOTIxVDEwNDg1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlODU5MzkwZDA5YjllNTFkNDk0NTVlZDJhOTAzMGE1MDdjMTU4MTkwM2EyYjY2OTMwNTJiNmU3ZjVjZTBkYjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LZmupqYQX93gJmeMLa3bwFsVWxJtcguHA7mdIhBr-7s">
> {
>   "minecraft:iron_chestplate":[
>     {
>       "attribute": "additional_attributes:innate_spell/irons_spellbooks/cloud_of_regeneration",
>       "modify": 2,
>       "uuid": "a516026a-bee2-4014-bcb6-b6a5775553de",
>       "operation": "ADDITION"
>     }
>   ]
> }
> ~Though the `ADD_VALUE` seems to be broken / their github code does not match their released state~ Actually might just have been added with 1.21
> 
> ```
> java.lang.IllegalArgumentException: No enum constant jackiecrazy.attributizer.ItemAttributeMod.Operation.ADD_VALUE
> 	at java.base/java.lang.Enum.valueOf(Enum.java:273)
> 	at TRANSFORMER/attributizer@3.1/jackiecrazy.attributizer.ItemAttributeMod$Operation.valueOf(ItemAttributeMod.java:53)
> 	at TRANSFORMER/attributizer@3.1/jackiecrazy.attributizer.ArmorAttributizer.lambda$apply$4(ArmorAttributizer.java:126)
> ```

Thank you for quick response!  It worked
